In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
patient_data = pd.read_csv("postoperativedata.csv")

In [3]:
patient_data

L-CORE L-SURF       L-O2  L-BP SURF-STBL CORE-STBL     BP-STBL  COMFORT  \
0      mid    low  excellent   mid    stable    stable      stable       15   
1      mid   high  excellent  high    stable    stable      stable       10   
2     high    low  excellent  high    stable    stable  mod-stable       10   
3      mid    low       good  high    stable  unstable  mod-stable       15   
4      mid    mid  excellent  high    stable    stable      stable       10   
..     ...    ...        ...   ...       ...       ...         ...      ...   
535    mid    mid  excellent   mid  unstable    stable      stable       10   
536    mid    mid  excellent   mid  unstable    stable      stable       15   
537    mid    mid       good   mid  unstable    stable      stable       15   
538    mid    mid  excellent   mid  unstable    stable      stable       10   
539    mid    mid       good   mid  unstable    stable      stable       15   

    decision ADM-DECS  
0                   A  
1                   S  
2                   A  
3                   A  
4                   A  
..                ...  
535                 A  
536                 S  
537                 A  
538                 A  
539                 S  

[540 rows x 9 columns]

In [4]:
patient_data.columns

Index(['L-CORE', 'L-SURF', 'L-O2', 'L-BP', 'SURF-STBL', 'CORE-STBL', 'BP-STBL',
       'COMFORT', 'decision ADM-DECS'],
      dtype='object')

In [5]:
patient_data.shape

(540, 9)

In [6]:
patient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   L-CORE             540 non-null    object
 1   L-SURF             540 non-null    object
 2   L-O2               540 non-null    object
 3   L-BP               540 non-null    object
 4   SURF-STBL          540 non-null    object
 5   CORE-STBL          540 non-null    object
 6   BP-STBL            540 non-null    object
 7   COMFORT            540 non-null    int64 
 8   decision ADM-DECS  540 non-null    object
dtypes: int64(1), object(8)
memory usage: 38.1+ KB


In [7]:
patient_data.isnull().sum()

L-CORE               0
L-SURF               0
L-O2                 0
L-BP                 0
SURF-STBL            0
CORE-STBL            0
BP-STBL              0
COMFORT              0
decision ADM-DECS    0
dtype: int64

In [8]:
for i in patient_data.columns:
    print(i)
    print(patient_data[i].nunique())
    print(patient_data[i].unique())

L-CORE
3
['mid' 'high' 'low']
L-SURF
3
['low' 'high' 'mid']
L-O2
2
['excellent' 'good']
L-BP
3
['mid' 'high' 'low']
SURF-STBL
2
['stable' 'unstable']
CORE-STBL
3
['stable' 'unstable' 'mod-stable']
BP-STBL
3
['stable' 'mod-stable' 'unstable']
COMFORT
5
[15 10  5  7 17]
decision ADM-DECS
2
['A' 'S']


In [9]:
for i in patient_data.columns:
    print(i)
    print(patient_data[i].nunique())
    print(patient_data[i].value_counts())

L-CORE
3
mid     348
low     114
high     78
Name: L-CORE, dtype: int64
L-SURF
3
mid     288
low     150
high    102
Name: L-SURF, dtype: int64
L-O2
2
good         282
excellent    258
Name: L-O2, dtype: int64
L-BP
3
mid     342
high    180
low      18
Name: L-BP, dtype: int64
SURF-STBL
2
stable      270
unstable    270
Name: SURF-STBL, dtype: int64
CORE-STBL
3
stable        498
unstable       36
mod-stable      6
Name: CORE-STBL, dtype: int64
BP-STBL
3
stable        276
unstable      138
mod-stable    126
Name: BP-STBL, dtype: int64
COMFORT
5
10    396
15    121
5      12
7       6
17      5
Name: COMFORT, dtype: int64
decision ADM-DECS
2
A    384
S    156
Name: decision ADM-DECS, dtype: int64


In [10]:
char_columns = []
for i in patient_data.columns:
    if patient_data[i].dtypes == "object":
        char_columns.append(i)

In [11]:
char_columns

['L-CORE',
 'L-SURF',
 'L-O2',
 'L-BP',
 'SURF-STBL',
 'CORE-STBL',
 'BP-STBL',
 'decision ADM-DECS']

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
label = LabelEncoder()

In [14]:
for i in char_columns:
    patient_data[i] = label.fit_transform(patient_data[i])

In [15]:
patient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   L-CORE             540 non-null    int32
 1   L-SURF             540 non-null    int32
 2   L-O2               540 non-null    int32
 3   L-BP               540 non-null    int32
 4   SURF-STBL          540 non-null    int32
 5   CORE-STBL          540 non-null    int32
 6   BP-STBL            540 non-null    int32
 7   COMFORT            540 non-null    int64
 8   decision ADM-DECS  540 non-null    int32
dtypes: int32(8), int64(1)
memory usage: 21.2 KB


In [16]:
for i in patient_data.columns:
    print(i)
    print(patient_data[i].nunique())
    print(patient_data[i].unique())

L-CORE
3
[2 0 1]
L-SURF
3
[1 0 2]
L-O2
2
[0 1]
L-BP
3
[2 0 1]
SURF-STBL
2
[0 1]
CORE-STBL
3
[1 2 0]
BP-STBL
3
[1 0 2]
COMFORT
5
[15 10  5  7 17]
decision ADM-DECS
2
[0 1]


In [17]:
features = patient_data.drop(["decision ADM-DECS"], axis=1)

In [18]:
features

L-CORE  L-SURF  L-O2  L-BP  SURF-STBL  CORE-STBL  BP-STBL  COMFORT
0         2       1     0     2          0          1        1       15
1         2       0     0     0          0          1        1       10
2         0       1     0     0          0          1        0       10
3         2       1     1     0          0          2        0       15
4         2       2     0     0          0          1        1       10
..      ...     ...   ...   ...        ...        ...      ...      ...
535       2       2     0     2          1          1        1       10
536       2       2     0     2          1          1        1       15
537       2       2     1     2          1          1        1       15
538       2       2     0     2          1          1        1       10
539       2       2     1     2          1          1        1       15

[540 rows x 8 columns]

In [19]:
target = patient_data["decision ADM-DECS"]

In [20]:
target

0      0
1      1
2      0
3      0
4      0
      ..
535    0
536    1
537    0
538    0
539    1
Name: decision ADM-DECS, Length: 540, dtype: int32

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(
    features, target, train_size=0.9, random_state=10000
)

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
rf = RandomForestClassifier(n_estimators=100, random_state=0)

In [25]:
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=0)

In [26]:
rf_predict = rf.predict(x_test)

In [27]:
rf_predict

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1])

In [28]:
from sklearn.metrics import accuracy_score, classification_report

In [29]:
accuracy_score(y_test, rf_predict)

0.9444444444444444

In [30]:
print(classification_report(y_test, rf_predict))

              precision    recall  f1-score   support

           0       0.97      0.94      0.96        36
           1       0.89      0.94      0.92        18

    accuracy                           0.94        54
   macro avg       0.93      0.94      0.94        54
weighted avg       0.95      0.94      0.94        54



In [31]:
patient_data["decision ADM-DECS"].value_counts()

0    384
1    156
Name: decision ADM-DECS, dtype: int64

In [32]:
import pandas as pd
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy="auto", random_state=42)

X_resampled, y_resampled = smote.fit_resample(features, target)

In [34]:
y_resampled.value_counts()

0    384
1    384
Name: decision ADM-DECS, dtype: int64

In [35]:
features = X_resampled
target = y_resampled

In [36]:
x_train, x_test, y_train, y_test = train_test_split(
    features, target, train_size=0.9, random_state=10000
)

In [38]:
rf = RandomForestClassifier(n_estimators=100, random_state=0)

In [39]:
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=0)

In [40]:
rf_predict = rf.predict(x_test)

In [41]:
accuracy_score(y_test, rf_predict)

0.974025974025974

In [42]:
print(classification_report(y_test, rf_predict))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97        39
           1       0.95      1.00      0.97        38

    accuracy                           0.97        77
   macro avg       0.97      0.97      0.97        77
weighted avg       0.98      0.97      0.97        77



In [45]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.1, random_state=10000
)

svm_classifier = SVC(
    kernel="linear", C=1.0
)  # You can choose different kernels (linear, rbf, poly, etc.)

# Train the SVM classifier on the training data
svm_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = svm_classifier.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.5454545454545454
